create or replace function public.generate_qr_batch(
  p_quantity integer,
  p_generated_by text
)
returns table (
  generation_id uuid,
  start_qr_code text,
  end_qr_code text,
  quantity integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_generation_id uuid;
  v_generation_date date;
  v_date_prefix text;
  v_last_sequence integer;
  v_start_sequence integer;
  v_end_sequence integer;
  v_start_qr_code text;
  v_end_qr_code text;
begin
  if p_quantity is null or p_quantity <= 0 then
    raise exception 'Quantity must be greater than zero.';
  end if;

  if p_quantity > 9999 then
    raise exception 'Maximum QR generation quantity is 9999.';
  end if;

  if p_generated_by is null or trim(p_generated_by) = '' then
    raise exception 'Generated by is required.';
  end if;

  v_generation_date := current_date;
  v_date_prefix := to_char(v_generation_date, 'YYMMDD');

  -- Prevent simultaneous QR generation for the same day.
  perform pg_advisory_xact_lock(
    hashtext('qr_generation:' || v_generation_date::text)
  );

  -- Find the highest sequence generated today.
  select coalesce(
    max(
      cast(
        substring(qg.end_qr_code from 7 for 4)
        as integer
      )
    ),
    0
  )
  into v_last_sequence
  from public.qr_generation as qg
  where qg.generation_date = v_generation_date;

  v_start_sequence := v_last_sequence + 1;
  v_end_sequence := v_start_sequence + p_quantity - 1;

  if v_end_sequence > 9999 then
    raise exception 'Daily QR sequence limit of 9999 has been reached.';
  end if;

  v_start_qr_code :=
    v_date_prefix || lpad(v_start_sequence::text, 4, '0');

  v_end_qr_code :=
    v_date_prefix || lpad(v_end_sequence::text, 4, '0');

  insert into public.qr_generation (
    generation_date,
    start_qr_code,
    end_qr_code,
    quantity,
    generated_by,
    print_status
  )
  values (
    v_generation_date,
    v_start_qr_code,
    v_end_qr_code,
    p_quantity,
    trim(p_generated_by),
    'PENDING'
  )
  returning qr_generation.generation_id
  into v_generation_id;

  return query
  select
    v_generation_id,
    v_start_qr_code,
    v_end_qr_code,
    p_quantity;
end;
$$;