"""QR generation and management service."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from database.supabase_db import get_supabase_client
from utils.base36 import encode_base36


@dataclass(frozen=True)
class QRGenerationResult:
    """Result returned after generating a QR batch."""

    generation_id: str
    start_qr_code: str
    end_qr_code: str
    quantity: int
    print_status: str


def generate_qr_batch(
    quantity: int,
    generated_by: str,
) -> QRGenerationResult:
    """Reserve a QR range and create its QR master records."""

    if quantity <= 0:
        raise ValueError("Quantity must be greater than zero.")

    if not generated_by or not generated_by.strip():
        raise ValueError("Generated by is required.")

    generated_by = generated_by.strip()

    client = get_supabase_client()

    # Reserve the QR range.
    response = client.rpc(
        "generate_qr_batch",
        {
            "p_quantity": quantity,
            "p_generated_by": generated_by,
        },
    ).execute()

    if not response.data:
        raise RuntimeError("Unable to create QR generation batch.")

    batch = response.data[0]

    generation_id = str(batch["generation_id"])
    start_qr_code = batch["start_qr_code"]
    end_qr_code = batch["end_qr_code"]

    start_sequence = int(start_qr_code[6:])
    end_sequence = int(end_qr_code[6:])
    date_prefix = start_qr_code[:6]

    now = datetime.now(timezone.utc).isoformat()

    qr_rows = []

    for sequence in range(start_sequence, end_sequence + 1):
        qr_code = f"{date_prefix}{sequence:04d}"

        qr_rows.append(
            {
                "qr_code": qr_code,
                "cycle_count": 0,
                "qr_printed_ts": None,
                "flagged": False,
                "flag_mode": None,
                "flag_reason": None,
                "flag_device_id": None,
                "flagged_ts": None,
                "active_status": True,
                "discard_user": None,
                "discard_device_id": None,
                "discard_reason": None,
                "discard_ts": None,
                "created_ts": now,
                "updated_ts": now,
                "updated_by": generated_by,
                "qr_code_encoded": encode_base36(int(qr_code)),
            }
        )

    # Insert QR master records.
    client.table("qr_master").insert(qr_rows).execute()

    return QRGenerationResult(
        generation_id=generation_id,
        start_qr_code=start_qr_code,
        end_qr_code=end_qr_code,
        quantity=quantity,
        print_status=batch["print_status"],
    )