"""QR print history page."""

from datetime import date, timedelta

from nicegui import ui

from components.layout import application_layout
from database.supabase_db import get_supabase_client


def render_print_history() -> None:
    """Render QR print history."""

    with application_layout("Print History", "print_history"):

        ui.label(
            "View QR generation and print history."
        ).classes("text-subtitle1 text-grey-7 mb-4")

        with ui.card().classes("w-full p-6"):

            with ui.row().classes(
                "w-full items-end gap-4"
            ):

                from_date = ui.input(
                    "From Date",
                    value=date.today().isoformat(),
                ).props(
                    "outlined type=date"
                ).classes("w-48")

                to_date = ui.input(
                    "To Date",
                    value=date.today().isoformat(),
                ).props(
                    "outlined type=date"
                ).classes("w-48")

                status = ui.select(
                    ["PRINTED", "PENDING", "PARTIAL", "ALL"],
                    value="PRINTED",
                    label="Status",
                ).props("outlined").classes("w-48")

                search_button = ui.button(
                    "Search",
                    icon="search",
                ).props("no-caps")

            table = ui.table(
                columns=[
                    {
                        "name": "generated_ts",
                        "label": "Generated",
                        "field": "generated_ts",
                        "align": "left",
                    },
                    {
                        "name": "start_qr_code",
                        "label": "Start QR",
                        "field": "start_qr_code",
                    },
                    {
                        "name": "end_qr_code",
                        "label": "End QR",
                        "field": "end_qr_code",
                    },
                    {
                        "name": "quantity",
                        "label": "Quantity",
                        "field": "quantity",
                    },
                    {
                        "name": "generated_by",
                        "label": "Generated By",
                        "field": "generated_by",
                    },
                    {
                        "name": "print_status",
                        "label": "Status",
                        "field": "print_status",
                    },
                ],
                rows=[],
                row_key="generation_id",
            ).classes("w-full mt-6")

            async def load_history() -> None:
                try:
                    from_value = from_date.value
                    to_value = to_date.value

                    if not from_value or not to_value:
                        ui.notify(
                            "Please select both dates.",
                            type="warning",
                        )
                        return

                    if from_value > to_value:
                        ui.notify(
                            "From Date cannot be after To Date.",
                            type="warning",
                        )
                        return

                    start_date = date.fromisoformat(
                        from_value
                    )

                    end_date = date.fromisoformat(
                        to_value
                    )

                    end_exclusive = (
                        end_date + timedelta(days=1)
                    ).isoformat()

                    client = get_supabase_client()

                    query = (
                        client.table("qr_generation")
                        .select(
                            "generation_id,"
                            "generated_ts,"
                            "start_qr_code,"
                            "end_qr_code,"
                            "quantity,"
                            "generated_by,"
                            "print_status"
                        )
                        .gte(
                            "generated_ts",
                            f"{start_date.isoformat()}T00:00:00",
                        )
                        .lt(
                            "generated_ts",
                            f"{end_exclusive}T00:00:00",
                        )
                        .order(
                            "generated_ts",
                            desc=True,
                        )
                    )

                    selected_status = status.value

                    if selected_status != "ALL":
                        query = query.eq(
                            "print_status",
                            selected_status,
                        )

                    response = query.execute()

                    table.rows = response.data or []
                    table.update()

                except Exception as exc:
                    ui.notify(
                        f"Unable to load history: {exc}",
                        type="negative",
                    )

            search_button.on_click(load_history)

            ui.timer(
                0.2,
                load_history,
                once=True,
            )