"""QR print history page."""

from datetime import date, timedelta

from nicegui import ui

from components.layout import application_layout
from database.supabase_db import get_supabase_client
from services.printer_service import (
    get_printer_status,
    print_qr_batch,
)


def render_print_history() -> None:
    """Render QR print history."""

    with application_layout("Print History", "print_history"):

        ui.label(
            "View QR generation and print history."
        ).classes("text-subtitle1 text-grey-7 mb-4")

        with ui.card().classes("w-full p-6"):

            with ui.row().classes(
                "w-full items-end gap-4"
            ):

                from_date = ui.input(
                    "From Date",
                    value=date.today().isoformat(),
                ).props(
                    "outlined type=date"
                ).classes("w-48")

                to_date = ui.input(
                    "To Date",
                    value=date.today().isoformat(),
                ).props(
                    "outlined type=date"
                ).classes("w-48")

                status = ui.select(
                    ["PRINTED", "PENDING", "PARTIAL", "ALL"],
                    value="PRINTED",
                    label="Status",
                ).props("outlined").classes("w-48")

                search_button = ui.button(
                    "Search",
                    icon="search",
                ).props("no-caps")

            table = ui.table(
                columns=[
                    {
                        "name": "generated_ts",
                        "label": "Generated",
                        "field": "generated_ts",
                        "align": "left",
                    },
                    {
                        "name": "start_qr_code",
                        "label": "Start QR",
                        "field": "start_qr_code",
                    },
                    {
                        "name": "end_qr_code",
                        "label": "End QR",
                        "field": "end_qr_code",
                    },
                    {
                        "name": "quantity",
                        "label": "Quantity",
                        "field": "quantity",
                    },
                    {
                        "name": "generated_by",
                        "label": "Generated By",
                        "field": "generated_by",
                    },
                    {
                        "name": "print_status",
                        "label": "Status",
                        "field": "print_status",
                    },
                    {
                        "name": "actions",
                        "label": "Action",
                        "field": "actions",
                    },
                ],
                rows=[],
                row_key="generation_id",
            ).classes("w-full mt-6")

            # ---------------------------------------------------------
            # Reprint
            # ---------------------------------------------------------

            async def reprint_generation(row: dict) -> None:
                """Reprint all QR codes belonging to one generation."""

                try:
                    # 1. Check printer before doing anything.
                    printer_status = get_printer_status()

                    if not printer_status["connected"]:
                        ui.notify(
                            "Printer not connected. "
                            "Please connect the printer and try again.",
                            type="negative",
                        )
                        return

                    start_qr = row.get("start_qr_code")
                    end_qr = row.get("end_qr_code")

                    if not start_qr or not end_qr:
                        ui.notify(
                            "Invalid QR range in print history.",
                            type="negative",
                        )
                        return

                    quantity = row.get("quantity", 0)

                    # 2. Ask for confirmation.
                    with ui.dialog() as dialog:
                        with ui.card().classes("w-96 p-6"):

                            ui.label(
                                "Confirm Reprint"
                            ).classes(
                                "text-h6 text-weight-medium"
                            )

                            ui.separator().classes("my-3")

                            ui.label(
                                f"Reprint {quantity} QR codes?"
                            ).classes("text-body1")

                            ui.label(
                                f"{start_qr}  →  {end_qr}"
                            ).classes(
                                "text-body2 text-grey-7 mt-2"
                            )

                            with ui.row().classes(
                                "w-full justify-end gap-3 mt-6"
                            ):

                                ui.button(
                                    "Cancel",
                                    on_click=dialog.close,
                                ).props("no-caps")

                                async def confirm_reprint() -> None:
                                    dialog.close()

                                    try:
                                        # Check printer again immediately
                                        # before submitting the print job.
                                        printer_status = (
                                            get_printer_status()
                                        )

                                        if not printer_status["connected"]:
                                            ui.notify(
                                                "Printer not connected. "
                                                "Please connect the printer "
                                                "and try again.",
                                                type="negative",
                                            )
                                            return

                                        client = get_supabase_client()

                                        # 3. Get the encoded QR values for
                                        # the selected generation range.
                                        response = (
                                            client.table("qr_master")
                                            .select(
                                                "qr_code,qr_code_encoded"
                                            )
                                            .gte(
                                                "qr_code",
                                                start_qr,
                                            )
                                            .lte(
                                                "qr_code",
                                                end_qr,
                                            )
                                            .order(
                                                "qr_code",
                                                desc=False,
                                            )
                                            .execute()
                                        )

                                        records = response.data or []

                                        if not records:
                                            ui.notify(
                                                "No QR codes found "
                                                "for this generation.",
                                                type="negative",
                                            )
                                            return

                                        encoded_values = [
                                            record["qr_code_encoded"]
                                            for record in records
                                            if record.get(
                                                "qr_code_encoded"
                                            )
                                        ]

                                        if not encoded_values:
                                            ui.notify(
                                                "No encoded QR values "
                                                "available for reprint.",
                                                type="negative",
                                            )
                                            return

                                        # 4. Print.
                                        print_qr_batch(
                                            encoded_values
                                        )

                                        ui.notify(
                                            f"Reprint submitted successfully "
                                            f"for {len(encoded_values)} QR codes.",
                                            type="positive",
                                        )

                                    except Exception as exc:
                                        ui.notify(
                                            f"Reprint failed: {exc}",
                                            type="negative",
                                        )

                                ui.button(
                                    "Reprint",
                                    icon="print",
                                    on_click=confirm_reprint,
                                ).props("no-caps").classes(
                                    "bg-primary text-white"
                                )

                    dialog.open()

                except Exception as exc:
                    ui.notify(
                        f"Reprint failed: {exc}",
                        type="negative",
                    )

            # ---------------------------------------------------------
            # Table action column
            # ---------------------------------------------------------

            table.add_slot(
                "body-cell-actions",
                """
                <q-td :props="props">
                    <q-btn
                        v-if="['PRINTED', 'PENDING', 'PARTIAL'].includes(props.row.print_status)"
                        flat
                        dense
                        no-caps
                        color="primary"
                        icon="print"
                        label="Reprint"
                        @click="$parent.$emit('reprint', props.row)"
                    >
                        <q-tooltip>Reprint QR codes</q-tooltip>
                    </q-btn>
                </q-td>
                """,
            )

            table.on(
                "reprint",
                lambda event: reprint_generation(event.args),
            )

            # ---------------------------------------------------------
            # Load history
            # ---------------------------------------------------------

            async def load_history() -> None:
                try:
                    from_value = from_date.value
                    to_value = to_date.value

                    if not from_value or not to_value:
                        ui.notify(
                            "Please select both dates.",
                            type="warning",
                        )
                        return

                    if from_value > to_value:
                        ui.notify(
                            "From Date cannot be after To Date.",
                            type="warning",
                        )
                        return

                    start_date = date.fromisoformat(
                        from_value
                    )

                    end_date = date.fromisoformat(
                        to_value
                    )

                    end_exclusive = (
                        end_date + timedelta(days=1)
                    ).isoformat()

                    client = get_supabase_client()

                    query = (
                        client.table("qr_generation")
                        .select(
                            "generation_id,"
                            "generated_ts,"
                            "start_qr_code,"
                            "end_qr_code,"
                            "quantity,"
                            "generated_by,"
                            "print_status"
                        )
                        .gte(
                            "generated_ts",
                            f"{start_date.isoformat()}T00:00:00",
                        )
                        .lt(
                            "generated_ts",
                            f"{end_exclusive}T00:00:00",
                        )
                        .order(
                            "generated_ts",
                            desc=True,
                        )
                    )

                    selected_status = status.value

                    if selected_status != "ALL":
                        query = query.eq(
                            "print_status",
                            selected_status,
                        )

                    response = query.execute()

                    table.rows = response.data or []
                    table.update()

                except Exception as exc:
                    ui.notify(
                        f"Unable to load history: {exc}",
                        type="negative",
                    )

            search_button.on_click(load_history)

            ui.timer(
                0.2,
                load_history,
                once=True,
            )